name: newone

on: 
  push:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: demo
        run: echo "Hello Gowda"
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: first
        run: echo "Do u want to know the name , and the name is ${{secrets.SECRET}} , ${{secrets.DOLO}}"