name: newone

on: 
  push:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: demo
        run: echo "Hello Gowda"
  demo:
    environment: NEW
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: second
        run: echo "The name of the person is ${{secrets.SORT}} , ${{secrets.VALUE}}"