name: newone

on: 
  push:
    branches:
      - master
  
  workflow_dispatch:
    inputs:
      demoinput:
        description: this is the input for the workflow
        required: true
        default: "Kiran"
    
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      greeting: ${{ steps.set-output-step.outputs.result }}
    steps:
      - name: Set Output
        id: set-output-step
        run: echo "result=Hello, GitHub Actions!" >> $GITHUB_OUTPUT
  demo:
    environment: NEW
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: second
        run: echo "The name of the person is ${{secrets.SORT}} , ${{secrets.VALUE}}"
      - name: third
        if: success()
        run: echo "The name is scuuess"
      - name: fifth
        run: echo "the name of the person is ${{inputs.demoinput}}"
    
  elicho:
    name: resuing wokrlow
    uses: ./.github/workflows/resuse.yml
